// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProfessionalListBlazor.Server.Data;

#nullable disable

namespace ProfessionalListBlazor.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241116162226_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProfessionalListBlazor.Shared.ProfessionalList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StyleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StyleId");

                    b.ToTable("ProfessionalLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Marisa Aparecida - Enfermeira",
                            Position = "(11)974836354 / Penha-Zona Leste, São Paulo",
                            StyleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "João Carlos - Psicólogo",
                            Position = "(11)937264738 / Tucuruvi - Zona Norte, São Paulo",
                            StyleId = 2
                        });
                });

            modelBuilder.Entity("ProfessionalListBlazor.Shared.Style", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Styles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sim"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Não"
                        });
                });

            modelBuilder.Entity("ProfessionalListBlazor.Shared.ProfessionalList", b =>
                {
                    b.HasOne("ProfessionalListBlazor.Shared.Style", "Style")
                        .WithMany()
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Style");
                });
#pragma warning restore 612, 618
        }
    }
}
